# Generated by Django 3.0.5 on 2020-08-29 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qazline', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subject',
            unique_together={('number', 'lesson')},
        ),
    ]
