# Generated by Django 3.0.5 on 2020-08-31 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qazline', '0002_auto_20200829_1929'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignmentmaterial',
            old_name='description',
            new_name='topic',
        ),
        migrations.RenameField(
            model_name='imagematerial',
            old_name='description',
            new_name='topic',
        ),
        migrations.RenameField(
            model_name='videomaterial',
            old_name='description',
            new_name='topic',
        ),
    ]
