# Generated by Django 3.0.5 on 2020-09-04 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qazline', '0004_auto_20200904_1852'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='type',
            new_name='question_type',
        ),
    ]
