# Generated by Django 3.0.5 on 2020-09-04 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qazline', '0005_auto_20200904_1951'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='question_type',
            new_name='task_type',
        ),
    ]
