# Generated by Django 3.1.5 on 2021-01-28 01:56

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import qazline.models
import qazline.validators


class Migration(migrations.Migration):

    dependencies = [
        ('qazline', '0006_auto_20200904_1952'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lesson',
            old_name='number',
            new_name='numeral',
        ),
        migrations.RenameField(
            model_name='subject',
            old_name='number',
            new_name='numeral',
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to=qazline.models.get_path_for_image, validators=[django.core.validators.validate_image_file_extension]),
        ),
        migrations.AlterField(
            model_name='task',
            name='answers',
            field=models.JSONField(validators=[qazline.validators.JSONSchemaValidator(limit_value={'items': {'additionalProperties': False, 'properties': {'answer_text': {'type': 'string'}, 'correct': {'type': 'boolean'}}, 'required': ['answer_text'], 'type': 'object'}, 'maxItems': 10, 'minItems': 1, 'type': 'array'})]),
        ),
        migrations.AlterField(
            model_name='task',
            name='quiz_material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='qazline.quizmaterial'),
        ),
        migrations.AlterUniqueTogether(
            name='subject',
            unique_together={('numeral', 'lesson')},
        ),
    ]
